# Generated by Django 6.0 on 2025-12-28 15:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CicloMenstrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('sintomas', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CiclosMenstruais',
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
            ],
            options={
                'db_table': 'Despesas',
            },
        ),
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refeicao', models.CharField(choices=[('Cafe', 'Café da Manhã'), ('Almoco', 'Almoço'), ('Jantar', 'Jantar'), ('Lanche', 'Lanche')], max_length=50)),
                ('alimentos', models.TextField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Dieta',
            },
        ),
        migrations.CreateModel(
            name='EntradaDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'EntradasDiario',
            },
        ),
        migrations.CreateModel(
            name='Gravidez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semanas_gestacao', models.IntegerField()),
                ('notas_medicas', models.TextField(blank=True, null=True)),
                ('data_importante', models.DateField(blank=True, null=True)),
                ('descricao_data', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Gravidez',
            },
        ),
        migrations.CreateModel(
            name='Hidratacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copos_bebidos', models.IntegerField(default=0)),
                ('meta_copos', models.IntegerField(default=8)),
                ('data', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Hidratacao',
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Lendo', 'Lendo'), ('Lido', 'Lido'), ('Quero Ler', 'Quero Ler')], max_length=50)),
            ],
            options={
                'db_table': 'Livros',
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
            ],
            options={
                'db_table': 'Receitas',
            },
        ),
    ]
