# Generated by Django 6.0 on 2025-12-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfil_gravidez_humor'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradadiario',
            name='humor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='entradadiario',
            table='EntradaDiario',
        ),
    ]
