# Generated by Django 6.0 on 2025-12-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('altura', models.FloatField(help_text='Altura em metros')),
                ('peso', models.FloatField(help_text='Peso em kg')),
                ('data_nascimento', models.DateField()),
                ('fase_vida', models.CharField(choices=[('Normal', 'Normal'), ('Gestante', 'Gestante'), ('Tentante', 'Tentante'), ('Lactante', 'Lactante')], default='Normal', max_length=50)),
                ('objetivo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Perfil',
            },
        ),
        migrations.AddField(
            model_name='gravidez',
            name='humor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
